name: "Javascript: amazon-cognito"

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: ./codeql/init
      with: 
        tools: ${{ secrets.CODEQL_CLI_URL }}
        language: javascript
    - uses: ./codeql/finish
      #working-directory: repos/amazon-cognito-js
