name: "Java: commons-io"

on:
  push:
    branches-ignore:
      - 'separate_workflow'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Copy bash to SIP free area for OSX
      if: matrix.os == 'macOS-latest'
      run: |
         cp /bin/bash /usr/local/bin/
    - uses: ./codeql-setup
      with: 
        tools: ${{ secrets.CODEQL_CLI_URL }}
        language: java
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package '-Dmaven.test.skip=true' '-Drat.skip=true' --file repos/commons-io/pom.xml
    - uses: ./codeql-main
