name: "Javascript end-to-end: amazon-cognito"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: change to src dir
      run: cd ./repos/amazon-cognito-js
    - name: analysis
      uses: ./codeql-self-contained
      with:
        language: javascript
        tools: ${{ secrets.CODEQL_URL }}
        license: ${{ secrets.CODEQL_LICENSE_URL }}
#    - uses: actions/upload-artifact@master
#      with:
#        name: snapshot
#        path: project
