name: "C#: SmartSql"

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: ./codeql-setup
      with: 
        tools: ${{ secrets.CODEQL_CLI_URL }}
    - name: Build SmartSql with dotnet
      run: |
        export DOTNET_CLI_TELEMETRY_OPTOUT=1
        export SEMMLE_CLRTRACER_CONSOLE=1
        export SEMMLE_CLRTRACER_VERBOSITY=3
        export SEMMLE_DEBUG_TRACER=10000
        cp bin/libtrace.dylib /Users/runner/hostedtoolcache/CodeQL/1.0.0/x64/codeql/tools/osx64
        cd repos/SmartSql
        export SEMMLE_DEBUG_TRACER=10000
        codeql database create ../../../database -l csharp -c "dotnet build SmartSql.sln" &
        PID=$!
        sleep 60
        ps -E -u `whoami`
        kill -9 $PID
        echo "===="
        dotnet --version
        dotnet --list-runtimes
        dotnet --lits-sdks
        echo "===="
        ls -l /Users/runner/hostedtoolcache/CodeQL/1.0.0/x64/codeql/
        xattr -l /Users/runner/hostedtoolcache/CodeQL/1.0.0/x64/codeql/tools/osx64/libtrace.dylib
        echo "===="
        cat  ../../../database/log/build-tracer.log
