name: "C#: SmartSql"

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: ./codeql-setup
      with: 
        tools: ${{ secrets.CODEQL_CLI_URL }}
    - name: Build SmartSql with dotnet
      run: |
        cd repos/SmartSql
        export SEMMLE_DEBUG_TRACER=10000
        codeql database create ../../../database -l csharp -c "dotnet build SmartSql.sln" &
        PID=$!
        sleep 120
        ps -E -u `whoami`
        kill -9 $PID
