name: "Test typescript-action"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run: |
        wget -q ${{ secrets.CODEQL_CLI_URL }} -O codeql.zip
        unzip -q codeql.zip
        ls -l
        codeql/codeql database create out --language=csharp --command='dotnet build'

